name: Run Tests with ts-node

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests with ts-node
      run: npx ts-node node_modules/.bin/jest

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results.xml

  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run SoapUI Tests
        run: |
          wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.6.0/SoapUI-5.6.0-linux-bin.tar.gz
          tar -xzf SoapUI-5.6.0-linux-bin.tar.gz
          ./SoapUI-5.6.0/bin/testrunner.sh -s"API-Testing" -r -a "./test/API-Testing-Avans-soapui-project.xml"
